const stateData = {
    "Andhra Pradesh": { image: "/images/states/ap.jpg", livesImpacted: "800k+" },
    "Arunachal Pradesh": { image: "/images/states/arunachal.jpg", livesImpacted: "50k+" },
    "Assam": { image: "/images/states/assam.jpg", livesImpacted: "200k+" },
    "Bihar": { image: "/images/states/bihar.jpg", livesImpacted: "1.5M+" },
    "Chhattisgarh": { image: "/images/states/cg.jpg", livesImpacted: "300k+" },
    "Goa": { image: "/images/states/goa.jpg", livesImpacted: "20k+" },
    "Gujarat": { image: "/images/states/gujarat.jpg", livesImpacted: "600k+" },
    "Haryana": { image: "/images/states/haryana.jpg", livesImpacted: "400k+" },
    "Himachal Pradesh": { image: "/images/states/hp.jpg", livesImpacted: "150k+" },
    "Jharkhand": { image: "/images/states/jharkhand.jpg", livesImpacted: "500k+" },
    "Karnataka": { image: "/images/states/karnataka.jpg", livesImpacted: "750k+" },
    "Kerala": { image: "/images/states/kerala.jpg", livesImpacted: "300k+" },
    "Madhya Pradesh": { image: "/images/states/mp.jpg", livesImpacted: "1.2M+" },
    "Maharashtra": { image: "/images/states/maharashtra.jpg", livesImpacted: "2M+" },
    "Manipur": { image: "/images/states/manipur.jpg", livesImpacted: "40k+" },
    "Meghalaya": { image: "/images/states/meghalaya.jpg", livesImpacted: "60k+" },
    "Mizoram": { image: "/images/states/mizoram.jpg", livesImpacted: "30k+" },
    "Nagaland": { image: "/images/states/nagaland.jpg", livesImpacted: "45k+" },
    "Odisha": { image: "/images/states/odisha.jpg", livesImpacted: "900k+" },
    "Punjab": { image: "/images/states/punjab.jpg", livesImpacted: "400k+" },
    "Rajasthan": { image: "/images/states/rajasthan.jpg", livesImpacted: "1.1M+" },
    "Sikkim": { image: "/images/states/sikkim.jpg", livesImpacted: "25k+" },
    "Tamil Nadu": { image: "/images/states/tn.jpg", livesImpacted: "850k+" },
    "Telangana": { image: "/images/states/telangana.jpg", livesImpacted: "600k+" },
    "Tripura": { image: "/images/states/tripura.jpg", livesImpacted: "70k+" },
    "Uttar Pradesh": { image: "/images/states/up.jpg", livesImpacted: "2.5M+" },
    "Uttarakhand": { image: "/images/states/uttarakhand.jpg", livesImpacted: "200k+" },
    "West Bengal": { image: "/images/states/wb.jpg", livesImpacted: "1.3M+" },
    "Jammu and Kashmir": { image: "/images/states/jk.jpg", livesImpacted: "100k+" }
};